-- Oracle Database Schema for PayDayLoan Application

-- Create tablespace if needed, but for simplicity, use default

-- Create sequence for IDs
CREATE SEQUENCE customer_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE loan_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE payment_seq START WITH 1 INCREMENT BY 1;

-- Create CUSTOMER table
CREATE TABLE CUSTOMER (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    PHONE VARCHAR2(20),
    ADDRESS VARCHAR2(255),
    CREATED_DATE DATE DEFAULT SYSDATE
);

-- Create LOAN table
CREATE TABLE LOAN (
    ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    INTEREST_RATE NUMBER(5,2) NOT NULL,
    TERM_MONTHS NUMBER NOT NULL,
    STATUS VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, APPROVED, REPAID, DEFAULTED
    REQUEST_DATE DATE DEFAULT SYSDATE,
    APPROVAL_DATE DATE,
    DUE_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

-- Create PAYMENT table
CREATE TABLE PAYMENT (
    ID NUMBER PRIMARY KEY,
    LOAN_ID NUMBER NOT NULL,
    AMOUNT NUMBER(10,2) NOT NULL,
    PAYMENT_DATE DATE DEFAULT SYSDATE,
    FOREIGN KEY (LOAN_ID) REFERENCES LOAN(ID)
);

-- Insert sample data
INSERT INTO CUSTOMER (ID, NAME, EMAIL, PHONE, ADDRESS) VALUES (customer_seq.NEXTVAL, 'John Doe', 'john.doe@example.com', '123-456-7890', '123 Main St');
INSERT INTO CUSTOMER (ID, NAME, EMAIL, PHONE, ADDRESS) VALUES (customer_seq.NEXTVAL, 'Jane Smith', 'jane.smith@example.com', '098-765-4321', '456 Elm St');

INSERT INTO LOAN (ID, CUSTOMER_ID, AMOUNT, INTEREST_RATE, TERM_MONTHS, STATUS, DUE_DATE) VALUES (loan_seq.NEXTVAL, 1, 500.00, 10.00, 1, 'APPROVED', ADD_MONTHS(SYSDATE, 1));
INSERT INTO LOAN (ID, CUSTOMER_ID, AMOUNT, INTEREST_RATE, TERM_MONTHS, STATUS, DUE_DATE) VALUES (loan_seq.NEXTVAL, 2, 1000.00, 15.00, 2, 'PENDING', ADD_MONTHS(SYSDATE, 2));

INSERT INTO PAYMENT (ID, LOAN_ID, AMOUNT) VALUES (payment_seq.NEXTVAL, 1, 550.00);

COMMIT;
