## Oracle profile
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.url=jdbc:oracle:thin:@192.168.20.77:1521/microcubepdb
spring.datasource.username=payday
spring.datasource.password=payday
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
