INSERT INTO PDL_CORPORATE (
    CORPORATE_ID, CORPORATE_CODE, CORPORATE_NAME, SHORT_NAME, CUSTOMER_ID,
    AGREEMENT_STATUS, AGREEMENT_DATE, EFFECTIVE_FROM, GUARANTEE_MODE,
    MAX_ELIGIBLE_PERCENT, SERVICE_CHARGE_PERCENT, MIN_SERVICE_CHARGE,
    MAX_ACTIVE_LOAN_PER_EMP, REPAYMENT_MODE, AUTO_DISBURSE_YN, STATUS,
    REMARKS, CREATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
    1, 'CORP001', 'Acme Corporation', 'ACME', 1001,
    'ACTIVE', CURRENT_DATE, CURRENT_DATE, 'CORPORATE_GUARANTEE',
    80.00, 2.00, 200.00,
    1, 'SALARY_DEDUCTION', 1, 'ACTIVE',
    'Seed corporate', 'SYSTEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO PDL_EMPLOYEE (
    EMPLOYEE_ID, CORPORATE_ID, EMPLOYEE_CODE, EMPLOYEE_NAME, CUSTOMER_ID,
    CIF_ID, MOBILE_NO, EMAIL, NID_NO, DESIGNATION, DEPARTMENT, JOIN_DATE,
    EMPLOYMENT_STATUS, SALARY_ACCOUNT_NO, REPAYMENT_ACCOUNT_NO, ELIGIBILITY_YN,
    STATUS, CREATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
    1, 1, 'EMP001', 'John Doe', 123,
    9001, '01712345678', 'john.doe@example.com', '1234567890', 'Engineer', 'Technology', CURRENT_DATE,
    'ACTIVE', 'SAL-001', 'REP-001', 1,
    'ACTIVE', 'SYSTEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO PDL_EMPLOYEE_SALARY (
    SALARY_ID, EMPLOYEE_ID, CORPORATE_ID, MONTHLY_SALARY, ELIGIBLE_PERCENT,
    MAX_ELIGIBLE_AMOUNT, EFFECTIVE_FROM, IS_CURRENT_YN, APPROVAL_STATUS,
    REMARKS, CREATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
    1, 1, 1, 100000.00, 80.00,
    80000.00, CURRENT_DATE, 1, 'APPROVED',
    'Seed salary', 'SYSTEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO PDL_PRODUCT_CONFIG (
    PRODUCT_CONFIG_ID, PRODUCT_CODE, PRODUCT_NAME, MAX_ELIGIBLE_PERCENT,
    SERVICE_CHARGE_PERCENT, MIN_SERVICE_CHARGE, MAX_ACTIVE_LOAN_PER_EMP,
    MIN_REQUEST_AMOUNT, MAX_REQUEST_AMOUNT, REPAYMENT_DUE_DAYS,
    EMPLOYER_APPROVAL_REQUIRED_YN, AUTO_DISBURSE_YN, STATUS,
    EFFECTIVE_FROM, CREATED_BY, CREATED_AT, UPDATED_AT
) VALUES (
    1, 'PDL001', 'Standard PayDay Loan', 80.00,
    2.00, 200.00, 1,
    500.00, 100000.00, 30,
    1, 1, 'ACTIVE',
    CURRENT_DATE, 'SYSTEM', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
